services:
  aethas38-core:
    build:
      context: .
      no_cache: true
    container_name: aethas38-multi-ia
    restart: unless-stopped
    ports:
      - "5002:5001"
    environment:
      - TZ=Europe/Paris
    env_file:
      - .env
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dockge-network

networks:
  dockge-network:
    external: true