services:
  aethas38-core:
    build: ./backend
    container_name: aethas38-core
    ports:
      - "5002:5001"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
      - ./sessions:/sessions
    restart: unless-stopped