name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Déclenche aussi le pipeline lors de la création d'un tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      # NOUVEAU : Génération dynamique des tags (SemVer + Latest)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gitea.aethas38.duckdns.org/xavier/multi-ia-codage
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}

      - name: Connexion au registre Gitea
        uses: docker/login-action@v2
        with:
          registry: gitea.aethas38.duckdns.org
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }} 

      - name: Build et Push de l'image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}