name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion au registre Gitea
        uses: docker/login-action@v2
        with:
          registry: gitea.aethas38.duckdns.org
          username: ${{ github.actor }}
          # Gitea génère ce token automatiquement lors de l'exécution
          password: ${{ secrets.GITEA_TOKEN }} 

      - name: Build et Push de l'image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gitea.aethas38.duckdns.org/xavier/multi-ia-codage:latest